Repository swsnu/swpp2019-team12, pull requests merged in 2019-11, with the labels that each got.

#32 Sonar cloud
  .travis.yml
  sonar-project.properties
Labels: Common

#38 [FE] SignUp, SignIn, SignOut 구현.
  .eslintrc.json
  .gitignore
  package-lock.json
  package.json
  server/meetingoverflow/serializers.py
  server/meetingoverflow/urls.py
  server/meetingoverflow/views.py
  src/App.js
  src/App.scss
  src/component/NotFound.jsx
  src/component/SignOut.jsx
  src/component/signup/Label.jsx
  src/container/Dashboard.jsx
  src/container/note/Note.jsx
  src/container/user/Account.jsx
  src/container/user/SignIn.jsx
  src/container/user/SignUp.jsx
  src/container/user/account.jsx
  src/container/user/signin.jsx
  src/container/user/signup.jsx
  src/container/workspace/Workspace.jsx
  src/index.js
  src/styles/Button.scss
  src/styles/Color.scss
  src/styles/Helper.scss
  src/styles/container/Label.scss
  src/styles/container/SignUp.scss
  yarn.lock
Labels: Frontend

#40 Be/feature/models🧵
  server/meetingoverflow/models.py
Labels: Backend

#30 [FE/DEV] Workspace Selection / Dashboard
  server/meetingoverflow/models.py
  server/meetingoverflow/serializers.py
  server/meetingoverflow/urls.py
  server/meetingoverflow/views.py
  src/App.js
  src/App.scss
  src/assets/icons/bullet_icon.svg
  src/assets/icons/check_icon.svg
  src/assets/icons/member_default_icon.svg
  src/assets/icons/note_icon.svg
  src/assets/icons/plus_icon.svg
  src/assets/icons/settings_icon.svg
  src/component/SignOut.jsx
  src/component/workspace-selection/SelectionCard.jsx
  src/component/workspace_leftbar/CreateNote.jsx
  src/component/workspace_leftbar/Label.jsx
  src/component/workspace_leftbar/MemberInfo.jsx
  src/component/workspace_leftbar/SettingInfo.jsx
  src/component/workspace_leftbar/WorkspaceInfo.jsx
  src/component/workspace_main/AgendaOverview.jsx
  src/component/workspace_main/Label.jsx
  src/component/workspace_main/MeetingNoteOverview.jsx
  src/component/workspace_main/OverviewCard.jsx
  src/container/Dashboard.jsx
  src/container/user/Account.jsx
  src/container/user/SignIn.jsx
  src/container/user/SignUp.jsx
  src/container/workspace/CreateModal.jsx
  src/container/workspace/Workspace.jsx
  src/container/workspace/WorkspaceSelection.jsx
  src/index.js
  src/styles/Button.scss
  src/styles/Input.scss
  src/styles/Overlay.scss
  src/styles/component/workspace_leftbar/CreateNote.scss
  src/styles/component/workspace_leftbar/Label.scss
  src/styles/component/workspace_leftbar/MemberInfo.scss
  src/styles/component/workspace_leftbar/SettingInfo.scss
  src/styles/component/workspace_leftbar/WorkspaceInfo.scss
  src/styles/component/workspace_main/AgendaOverview.scss
  src/styles/component/workspace_main/Label.scss
  src/styles/component/workspace_main/MeetingNoteOverview.scss
  src/styles/component/workspace_selection/SelectionCard.scss
  src/styles/container/CreateModal.scss
  src/styles/container/Workspace.scss
  src/styles/container/WorkspaceSelection.scss
  src/styles/normalize.scss
Labels: Frontend

#43 Be/feature/api
  server/meetingoverflow/models.py
  server/meetingoverflow/serializers.py
  server/meetingoverflow/urls.py
  server/meetingoverflow/views.py
Labels: Backend

#41 [FE/DEV] Create Note Modal 구현
  package.json
  server/meetingoverflow/models.py
  server/meetingoverflow/serializers.py
  server/meetingoverflow/urls.py
  server/meetingoverflow/views.py
  src/App.scss
  src/component/workspace-selection/SelectionCard.jsx
  src/component/workspace_leftbar/CreateNote.jsx
  src/component/workspace_leftbar/WorkspaceInfo.jsx
  src/component/workspace_main/MeetingNoteOverview.jsx
  src/component/workspace_main/OverviewCard.jsx
  src/container/note/CreateModal.jsx
  src/container/workspace/CreateModal.jsx
  src/container/workspace/Workspace.jsx
  src/container/workspace/WorkspaceSelection.jsx
  src/styles/Datetime.scss
  src/styles/component/workspace_selection/SelectionCard.scss
  src/styles/container/CreateModal.scss
  yarn.lock
Labels: Frontend
